"""empty message

Revision ID: 3f2c64cd79df
Revises: 11210f793b20
Create Date: 2014-10-13 13:24:51.044184

"""

# revision identifiers, used by Alembic.
revision = '3f2c64cd79df'
down_revision = '11210f793b20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
